// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetserviceClient is the client API for Greetservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetserviceClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (Greetservice_SayHelloServerStreamingClient, error)
	SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Greetservice_SayHelloClientStreamingClient, error)
	SayHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (Greetservice_SayHelloBidirectionalStreamingClient, error)
}

type greetserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetserviceClient(cc grpc.ClientConnInterface) GreetserviceClient {
	return &greetserviceClient{cc}
}

func (c *greetserviceClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.Greetservice/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetserviceClient) SayHelloServerStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (Greetservice_SayHelloServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greetservice_ServiceDesc.Streams[0], "/greet_service.Greetservice/SayHelloServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetserviceSayHelloServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greetservice_SayHelloServerStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetserviceSayHelloServerStreamingClient struct {
	grpc.ClientStream
}

func (x *greetserviceSayHelloServerStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetserviceClient) SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (Greetservice_SayHelloClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greetservice_ServiceDesc.Streams[1], "/greet_service.Greetservice/SayHelloClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetserviceSayHelloClientStreamingClient{stream}
	return x, nil
}

type Greetservice_SayHelloClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetserviceSayHelloClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetserviceSayHelloClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetserviceSayHelloClientStreamingClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetserviceClient) SayHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (Greetservice_SayHelloBidirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greetservice_ServiceDesc.Streams[2], "/greet_service.Greetservice/SayHelloBidirectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetserviceSayHelloBidirectionalStreamingClient{stream}
	return x, nil
}

type Greetservice_SayHelloBidirectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetserviceSayHelloBidirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetserviceSayHelloBidirectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetserviceSayHelloBidirectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetserviceServer is the server API for Greetservice service.
// All implementations must embed UnimplementedGreetserviceServer
// for forward compatibility
type GreetserviceServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHelloServerStreaming(*NamesList, Greetservice_SayHelloServerStreamingServer) error
	SayHelloClientStreaming(Greetservice_SayHelloClientStreamingServer) error
	SayHelloBidirectionalStreaming(Greetservice_SayHelloBidirectionalStreamingServer) error
	mustEmbedUnimplementedGreetserviceServer()
}

// UnimplementedGreetserviceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetserviceServer struct {
}

func (UnimplementedGreetserviceServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetserviceServer) SayHelloServerStreaming(*NamesList, Greetservice_SayHelloServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloServerStreaming not implemented")
}
func (UnimplementedGreetserviceServer) SayHelloClientStreaming(Greetservice_SayHelloClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloClientStreaming not implemented")
}
func (UnimplementedGreetserviceServer) SayHelloBidirectionalStreaming(Greetservice_SayHelloBidirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloBidirectionalStreaming not implemented")
}
func (UnimplementedGreetserviceServer) mustEmbedUnimplementedGreetserviceServer() {}

// UnsafeGreetserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetserviceServer will
// result in compilation errors.
type UnsafeGreetserviceServer interface {
	mustEmbedUnimplementedGreetserviceServer()
}

func RegisterGreetserviceServer(s grpc.ServiceRegistrar, srv GreetserviceServer) {
	s.RegisterService(&Greetservice_ServiceDesc, srv)
}

func _Greetservice_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetserviceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.Greetservice/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetserviceServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greetservice_SayHelloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetserviceServer).SayHelloServerStreaming(m, &greetserviceSayHelloServerStreamingServer{stream})
}

type Greetservice_SayHelloServerStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetserviceSayHelloServerStreamingServer struct {
	grpc.ServerStream
}

func (x *greetserviceSayHelloServerStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Greetservice_SayHelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetserviceServer).SayHelloClientStreaming(&greetserviceSayHelloClientStreamingServer{stream})
}

type Greetservice_SayHelloClientStreamingServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetserviceSayHelloClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetserviceSayHelloClientStreamingServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetserviceSayHelloClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greetservice_SayHelloBidirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetserviceServer).SayHelloBidirectionalStreaming(&greetserviceSayHelloBidirectionalStreamingServer{stream})
}

type Greetservice_SayHelloBidirectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetserviceSayHelloBidirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetserviceSayHelloBidirectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetserviceSayHelloBidirectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greetservice_ServiceDesc is the grpc.ServiceDesc for Greetservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greetservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.Greetservice",
	HandlerType: (*GreetserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greetservice_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloServerStreaming",
			Handler:       _Greetservice_SayHelloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloClientStreaming",
			Handler:       _Greetservice_SayHelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloBidirectionalStreaming",
			Handler:       _Greetservice_SayHelloBidirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
